// <auto-generated />
using System;
using ChampionsLeagueTickets.Domain.DataDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChampionsLeagueTickets.Domain.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20260416150016_AddTicketsPrijs")]
    partial class AddTicketsPrijs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Abonnementen", b =>
                {
                    b.Property<string>("AbonnementId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("abonnementID");

                    b.Property<string>("StadionId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("stadionID");

                    b.Property<DateOnly>("EindDatum")
                        .HasColumnType("date")
                        .HasColumnName("eindDatum");

                    b.Property<string>("SeizoenId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("seizoenID");

                    b.Property<DateOnly>("StartDatum")
                        .HasColumnType("date")
                        .HasColumnName("startDatum");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("userID");

                    b.Property<string>("ZitplaatsId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("zitplaatsID");

                    b.HasKey("AbonnementId", "StadionId")
                        .HasName("PK__Abonneme__CF3D39B38C8AC8F7");

                    b.HasIndex("SeizoenId");

                    b.HasIndex("UserId");

                    b.HasIndex("StadionId", "ZitplaatsId");

                    b.ToTable("Abonnementen", (string)null);
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Match", b =>
                {
                    b.Property<string>("MatchId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("matchID");

                    b.Property<string>("BezoekendTeamId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("bezoekendTeamID");

                    b.Property<DateTime>("DatumTijdStartMatch")
                        .HasColumnType("datetime")
                        .HasColumnName("datumTijdStartMatch");

                    b.Property<string>("ThuisTeamId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("thuisTeamID");

                    b.HasKey("MatchId")
                        .HasName("PK__Matches__02C72A2D6D040317");

                    b.HasIndex("BezoekendTeamId");

                    b.HasIndex("ThuisTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("orderID");

                    b.Property<DateTime>("DatumTijdOrder")
                        .HasColumnType("datetime")
                        .HasColumnName("datumTijdOrder");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("userID");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__0809337D408CD464");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Orderlijnen", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("orderID");

                    b.Property<int>("OrderLijnNummer")
                        .HasColumnType("int")
                        .HasColumnName("orderLijnNummer");

                    b.Property<string>("AbonnementId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("abonnementID");

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("bedrag");

                    b.Property<string>("MatchId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("matchID");

                    b.Property<string>("StadionId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("stadionID");

                    b.Property<string>("TicketId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ticketID");

                    b.HasKey("OrderId", "OrderLijnNummer")
                        .HasName("PK__Orderlij__BEA8F4E8FF672866");

                    b.HasIndex("AbonnementId", "StadionId");

                    b.HasIndex("TicketId", "MatchId");

                    b.ToTable("Orderlijnen", (string)null);
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Seizoenen", b =>
                {
                    b.Property<string>("SeizoenId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("seizoenID");

                    b.Property<DateOnly>("EindDatum")
                        .HasColumnType("date")
                        .HasColumnName("eindDatum");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("naam");

                    b.Property<DateOnly>("StartDatum")
                        .HasColumnType("date")
                        .HasColumnName("startDatum");

                    b.HasKey("SeizoenId")
                        .HasName("PK__Seizoene__C0EC0D7B16A4F77F");

                    b.ToTable("Seizoenen", (string)null);
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Stadion", b =>
                {
                    b.Property<string>("StadionId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("stadionID");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adres");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("gemeente");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("land");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("naam");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("postcode");

                    b.HasKey("StadionId")
                        .HasName("PK__Stadions__56AECC45BAFDAEA9");

                    b.ToTable("Stadions");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("teamID");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("naam");

                    b.Property<string>("StadionId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("stadionID");

                    b.HasKey("TeamId")
                        .HasName("PK__Teams__5ED7534A07296CA1");

                    b.HasIndex("StadionId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ticketID");

                    b.Property<string>("MatchId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("matchID");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prijs");

                    b.Property<string>("StadionId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("stadionID");

                    b.Property<string>("ZitplaatsId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("zitplaatsID");

                    b.HasKey("TicketId", "MatchId")
                        .HasName("PK__Tickets__F31FB4D279B38C40");

                    b.HasIndex("MatchId");

                    b.HasIndex("StadionId", "ZitplaatsId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.TicketsPrijs", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VakNummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MatchId", "VakNummer");

                    b.ToTable("TicketsPrijs");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.VakType", b =>
                {
                    b.Property<string>("VakNummer")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("vakNummer");

                    b.Property<string>("Omschrijving")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("omschrijving");

                    b.Property<int>("Ring")
                        .HasColumnType("int")
                        .HasColumnName("ring");

                    b.HasKey("VakNummer")
                        .HasName("PK__VakTypes__BBCA469A4C59D109");

                    b.ToTable("VakTypes");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Zitplaatsen", b =>
                {
                    b.Property<string>("StadionId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("stadionID");

                    b.Property<string>("ZitplaatsId")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("zitplaatsID");

                    b.Property<string>("RijNummer")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("rijNummer");

                    b.Property<string>("StoelNummer")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("stoelNummer");

                    b.Property<string>("VakNummer")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("vakNummer");

                    b.HasKey("StadionId", "ZitplaatsId")
                        .HasName("PK__Zitplaat__76B42E8743521A35");

                    b.HasIndex("VakNummer");

                    b.ToTable("Zitplaatsen", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Abonnementen", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Seizoenen", "Seizoen")
                        .WithMany("Abonnementens")
                        .HasForeignKey("SeizoenId")
                        .HasConstraintName("fk_seizoenID_Abonnementen");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Stadion", "Stadion")
                        .WithMany("Abonnementens")
                        .HasForeignKey("StadionId")
                        .IsRequired()
                        .HasConstraintName("fk_stadionID_Abonnementen");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUser", "User")
                        .WithMany("Abonnementens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Abonnementen_AspNetUsers");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Zitplaatsen", "Zitplaatsen")
                        .WithMany("Abonnementens")
                        .HasForeignKey("StadionId", "ZitplaatsId")
                        .IsRequired()
                        .HasConstraintName("fk_zitplaatsID_Abonnementen");

                    b.Navigation("Seizoen");

                    b.Navigation("Stadion");

                    b.Navigation("User");

                    b.Navigation("Zitplaatsen");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetRoleClaim", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUserClaim", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Match", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Team", "BezoekendTeam")
                        .WithMany("MatchBezoekendTeams")
                        .HasForeignKey("BezoekendTeamId")
                        .IsRequired()
                        .HasConstraintName("fk_bezoekendTeamID");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Team", "ThuisTeam")
                        .WithMany("MatchThuisTeams")
                        .HasForeignKey("ThuisTeamId")
                        .IsRequired()
                        .HasConstraintName("fk_thuisTeamID");

                    b.Navigation("BezoekendTeam");

                    b.Navigation("ThuisTeam");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Order", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Orderlijnen", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Order", "Order")
                        .WithMany("Orderlijnens")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_orderID_Orderlijnen");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Abonnementen", "Abonnementen")
                        .WithMany("Orderlijnens")
                        .HasForeignKey("AbonnementId", "StadionId")
                        .HasConstraintName("fk_abonnement_Orderlijnen");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Ticket", "Ticket")
                        .WithMany("Orderlijnens")
                        .HasForeignKey("TicketId", "MatchId")
                        .HasConstraintName("fk_ticket_Orderlijnen");

                    b.Navigation("Abonnementen");

                    b.Navigation("Order");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Team", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Stadion", "Stadion")
                        .WithMany("Teams")
                        .HasForeignKey("StadionId")
                        .IsRequired()
                        .HasConstraintName("fk_StadionID_Teams");

                    b.Navigation("Stadion");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Ticket", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Match", "Match")
                        .WithMany("Tickets")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("fk_matchID_Tickets");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Stadion", "Stadion")
                        .WithMany("Tickets")
                        .HasForeignKey("StadionId")
                        .IsRequired()
                        .HasConstraintName("fk_stadionID_Tickets");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Zitplaatsen", "Zitplaatsen")
                        .WithMany("Tickets")
                        .HasForeignKey("StadionId", "ZitplaatsId")
                        .IsRequired()
                        .HasConstraintName("fk_zitplaatsID_Tickets");

                    b.Navigation("Match");

                    b.Navigation("Stadion");

                    b.Navigation("Zitplaatsen");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Zitplaatsen", b =>
                {
                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.Stadion", "Stadion")
                        .WithMany("Zitplaatsens")
                        .HasForeignKey("StadionId")
                        .IsRequired()
                        .HasConstraintName("fk_stadionID_Zitplaatsen");

                    b.HasOne("ChampionsLeagueTickets.Domain.EntitiesDB.VakType", "VakNummerNavigation")
                        .WithMany("Zitplaatsens")
                        .HasForeignKey("VakNummer")
                        .IsRequired()
                        .HasConstraintName("fk_vakNummer_Zitplaatsen");

                    b.Navigation("Stadion");

                    b.Navigation("VakNummerNavigation");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Abonnementen", b =>
                {
                    b.Navigation("Orderlijnens");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.AspNetUser", b =>
                {
                    b.Navigation("Abonnementens");

                    b.Navigation("AspNetUserClaims");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Match", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Order", b =>
                {
                    b.Navigation("Orderlijnens");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Seizoenen", b =>
                {
                    b.Navigation("Abonnementens");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Stadion", b =>
                {
                    b.Navigation("Abonnementens");

                    b.Navigation("Teams");

                    b.Navigation("Tickets");

                    b.Navigation("Zitplaatsens");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Team", b =>
                {
                    b.Navigation("MatchBezoekendTeams");

                    b.Navigation("MatchThuisTeams");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Ticket", b =>
                {
                    b.Navigation("Orderlijnens");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.VakType", b =>
                {
                    b.Navigation("Zitplaatsens");
                });

            modelBuilder.Entity("ChampionsLeagueTickets.Domain.EntitiesDB.Zitplaatsen", b =>
                {
                    b.Navigation("Abonnementens");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
